# Generated by Django 3.2.10 on 2022-12-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('CM', 'Club Manager'), ('M', 'Member')], default='U', max_length=2),
        ),
    ]
