# Generated by Django 3.2.10 on 2022-12-03 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_clubs_club_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='pending_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='_clubs_club_pending_members_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
